### ISSUE TITLE
Doesn't seem to respect PATH

### ISSUE THREAD

**Issue by cscott** [naugtur/npm-audit-resolver#31]
```
cananian@skiffserv:~/Projects/Wikimedia/Parsoid$ which npm
/home/cananian/.nave/installed/10.15/bin/npm
cananian@skiffserv:~/Projects/Wikimedia/Parsoid$ npm --version
6.14.5
cananian@skiffserv:~/Projects/Wikimedia/Parsoid$ resolve-audit
>>>> npm audit --json 
npm WARN npm npm does not support Node.js v10.21.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
>>>> exit: 1
failed to parse output

Usage: npm <command>

where <command> is one of:
    access, adduser, bin, bugs, c, cache, ci, completion,
    config, ddp, dedupe, deprecate, dist-tag, docs, doctor,
    edit, explore, get, help, help-search, i, init, install,
    install-test, it, link, list, ln, login, logout, ls,
    outdated, owner, pack, ping, prefix, profile, prune,
    publish, rb, rebuild, repo, restart, root, run, run-script,
    s, se, search, set, shrinkwrap, star, stars, start, stop, t,
    team, test, token, tst, un, uninstall, unpublish, unstar,
    up, update, v, version, view, whoami

npm <command> -h     quick help on <command>
npm -l           display full usage info
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    /home/cananian/.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@5.8.0 /usr/share/npm

Did you mean this?
    edit

SyntaxError: Unexpected token U in JSON at position 1
    at JSON.parse (<anonymous>)
    at promiseCommand.then.output (/home/cananian/.nave/installed/10.15/lib/node_modules/npm-audit-resolver/src/pkgmanagers/npm.js:23:33)
    at process._tickCallback (internal/process/next_tick.js:68:7)
cananian@skiffserv:~/Projects/Wikimedia/Parsoid$ 
```

`resolve-audit` seems to be using the system npm (5.8.0) not the version of npm on the PATH (6.14.5).

**Comment by naugtur** [comment]
Thanks for reporting.   
Is this regular Bash on Linux or something else?

**Comment by naugtur** [comment]
I'd need more details or a simple way to reproduce. Closing as stale for now. Please share more details and reopen.
